# 22장 플로우 생명주기 함수

플로우

- 요청이 한쪽 방향으로 흐르고 요청에 의해 생성된 값이 다른 방향으로 흐르는 파이프라 생각할 수 있다.
- 완료되거나 예외가 발생했을 때, 이러한 정보가 전달되어 중간 단계가 종료된다.
- 모든 정보가 플로우로 전달되므로 값, 예외 및 다른 특정 이벤트를 감지할 수 있다.

## onEach

- 플로우의 값을 하나씩 받기 위해 사용한다.
- 중단 함수이며, 원소는 순서대로 처리된다.
- dealy를 넣으면 각각의 값이 흐를 때마다 지연되게 된다.

```kotlin
suspend fun main() {
	flowOf(1, 2, 3, 4) 
		.onEach { print(it) }
		.collect() // 1234
}
```

```kotlin
suspend fun main() {
	flowOf(1, 2)
		.onEach { delay(1000) }
		.collect { println(it) }
}
```

- 출력
    
    ```kotlin
    // (1초 후)
    // 1
    // (1초 후)
    // 2
    ```
    

## onStart

- 최종 연산이 호출될 때와 같이 플로우가 시작되는 경우에 호출되는 리스너를 설정한다.
- 첫 번째 원소가 생성되는 걸 기다렸다 호출되는 게 아니라는 것이 중요하다.
- 첫 번째 원소를 요청했을 때 호출되는 함수

```kotlin
suspend fun main() {
	flowOf(1, 2)
		.onEach { delay(1000) }
		.onStart { println("Before") }
		.collect { println(it) }
}
```

- 출력
    
    ```kotlin
    // Before
    // (1초 후)
    // 1
    // (1초 후)
    // 2
    ```
    

- onStart에서도 원소를 내보낼 수 있다.
    - 원소들은 onStart부터 아래로 흐르게 된다.

```kotlin
suspend fun main() {
	flowOf(1, 2) 
		.onEach { delay(1000) }
		.onStart { emit(0) }
		.collect { println(it) }
}
```

- 출력
    
    ```kotlin
    // 0
    // (1초 후)
    // 1
    // (1초 후)
    // 2
    ```
    

## onCompletion

플로우 완료할 수 있는 방법

- 잡히지 않은 예외 발생
- 코루틴이 취소되었을 때
- 플로우 빌더가 끝났을 때(예를 들면, 마지막 원소가 전송되었을 때)

onCompletion

- 플로우가 완료되었을 때 호출되는 리스너를 추가할 수 있다.

```kotlin
suspend fun main() = coroutineScope {
	flowOf(1, 2)
		.onEach { delay(1000) }
		.onCompletion { println("Completed") }
		.collect { println(it) }
}
```

- 출력
    
    ```kotlin
    // (1초 후)
    // 1
    // (1초 후)
    // 2
    // Completed
    ```
    

```kotlin
suspend fun main() = coroutineScope {
	val job = launch {
		flowOf(1, 2) 
			.onEach { delay(1000) }
			.onCompletion { println("Completed") }
			.collect { println(it) }
	}
	delay(1100)
	job.cancel()
}
```

- 출력
    
    ```kotlin
    // (1초 후)
    // 1
    // (0.1초 후)
    // Completed
    ```
    

안드로이드에서는 프로그레스바를 보여주기 위해 onStart를 사용하며, 가리기 위해서는 onCompletion을 사용한다.

```kotlin
fun updateNews() {
	scope.launch {
		newsFlow()
			.onStart { showProgressbar() }
			.onCompletion { hideProgressbar() }
			.collect { view.showNews(it) }
  }
}
```

## onEmpty

플로우는 예기치 않은 이벤트가 발생하면 값을 내보내기 전에 완료될 수 있다.

onEmpty

- 원소를 내보내기 전에 플로우가 완료되면 실행된다.
- 기본값을 내보내기 위한 목적으로 사용될 수 있다.

```kotlin
suspend fun main() = coroutineScope {
	flow<List<Int>> { delay(1000) }
		.onEmpty { emit(emptyList()) }
		.collect { println(it) }
}
```

- 출력
    
    ```kotlin
    // (1초 후)
    // []
    ```
    

## catch

플로우를 만들거나 처리하는 도중에 예외가 발생할 수 있다.

→ 이러한 예외는 아래로 흐르면서 처리하는 단계를 하나씩 닫는다.

catch

- 예외를 잡고 관리한다.
- 리스너는 예외를 인자로 받고 정리를 위한 연산을 수행할 수 있다.

```kotlin
class MyError : Throwable("My error")

val flow = flow {
	emit(1)
	emit(2)
	throw MyError() 
}

suspend fun main(): Unit {
	flow.onEach { println("Got $it") }
			.catch { println("Caught $it") }
			.collect { println("Collected $it") }
}
```

- 출력
    
    ```kotlin
    // Got 1
    // Collected 1
    // Got 2
    // Collected 2
    // Caught MyError: My Error
    ```
    

<aside>
💡 onEach는 예외에 반응하지 않는다.
map, filter와 같은 다른 함수에서도 마찬가지다.
오직 onCompletion 핸드러만 예외가 발생했을 때 호출한다.

</aside>

- 예외를 잡아 전파되는 걸 멈춘다.
- 새로운 값을 여전히 내보낼 수 있어 남은 플로우를 지속할 수 있다.

```kotlin
val flow = flow {
	emit("Message1")
	throw MyError()
}

suspend fun main(): Unit {
	flow.catch { emit("Error") }
		  .collect { println("Collected $it") }
}
```

- 출력
    
    ```kotlin
    // Collected Message1
    // Collected Error
    ```
    

- catch 함수의 윗부분에서 던진 예외에만 반응한다.(예외는 아래로 흐를 때 잡는다고 생각하면 된다)

![IMG_1D059EF33991-1](https://github.com/woowacourse-study/2023-BookOverFlow/assets/50761690/aa20aec7-9055-4308-a088-ef03a93f95f0)


안드로이드에서는 플로우에서 일어나는 예외를 보여주기 위해 catch를 주로 사용한다.

```kotlin
fun updateNews() {
	scope.launch {
		newsFlow() 
			.catch { view.handleError(it) }
			.onStart { showProgressBar() }
			.onCompletion { hideProgressBar() }
			.collect { view.showNews(it) }
	}
}
```

빈 리스트처럼 스크린에서 보여지는 기본값을 내보내기 위해 catch를 사용할 수도 있다.

```kotlin
fun updateNews() {
	scope.launch {
		newsFlow()
			.catch {
				view.handleError(it)
				emit(emptyList())
			}
			.onStart { showProgressBar() }
			.onCompletion { hideProgressBar() }
			.collect { view.showNews(it) }
 }
}
```

## 잡히지 않은 예외

플로우에서 잡히지 않은 예외는 플로우를 즉시 취소하며, collect는 예외를 다시 던진다.

중단 함수가 예외를 처리하는 방식과 같으며, coroutineScope 또한 같은 방식으로 예외를 처리한다.

플로우 바깥에서 전통적인 try-catch 블록을 사용해서 예외를 잡을 수도 있다.

```kotlin
val flow = flow {
	emit("Message1")
	throw MyError()
}

suspend fun main(): Unit {
	try {
		flow.collect { println("Collected $it") }
	} catch (e: MyError) {
		println("Caught")
	}
}
```

- 출력
    
    ```kotlin
    // Collected Message1
    // Caught
    ```
    

catch를 사용하는 건 최종 연산에서 발생한 예외를 처리하는데 도움이 되지 않는다.

→ collect에서 예외가 발생하면 예외를 잡지 못하게 되어 블록 밖으로 예외가 전달된다.

```kotlin
val flow = flow {
	emit("Message1")
	emit("Message2")
}

suspend fun main(): Unit {
	flow.onStart { println("Before") }
			.catch { println("Caught $it") }
			.collect { throw MyError() }
			
}
```

- 출력
    
    ```kotlin
    // Before
    // Exception in thread "..." MyError: My error
    ```
    

collect의 연산을 onEach로 옮기고 catch 이전에 두는 방법이 자주 사용된다.

→ collect의 연산을 옮긴다면 catch가 모든 예외를 잡을 수 있다.

```kotlin
val flow = flow {
	emit("Message1")
	emit("Message2")
}

suspend fun main(): Unit {
	flow.onStart { println("Before") }
			.onEach { throw MyError() }
			.catch { println("Caught $it") }
			.collect()
}
```

- 출력
    
    ```kotlin
    // Before
    // Caught MyError: My error
    ```
    

## flowOn

(onEach, onStart, onCompletion과 같은) 플로우 연산과 (flow나 channelFlow와 같은) 플로우 빌더의 인자로 사용되는 람다식은 모두 중단 함수이다. 

중단함수는 컨텍스트가 필요하며(구조화된 동시성을 위해) 부모와 관계를 유지한다.

플로우의 함수들의 컨텍스트 → collect가 호출되는 곳의 컨텍스트이다.

```kotlin
fun usersFlow(): Flow<String> = flow {
	repeat(2) {
		val ctx = currentCoroutineContext()
		val name = ctx[coroutineName]?.name
		emit("User$it in $name")
	}
}

suspend fun main() {
	val users = usersFlow()
	withContext(CoroutineName("Name1")) {
		users.collect { println(it) }
  }
  withContext(CoroutineName("Name2")) {
	  users.collect { printn(it) }
	}
}
```

- 출력
    
    ```kotlin
    // User0 in Name1
    // User1 in Name1
    // User0 in Name2
    // User1 in Name2
    ```
    

→ 최종 연산을 호출하면 상위에 있는 모든 원소를 요청하면서 코루틴 컨텍스트를 전달한다.

**flowOn**

- 컨텍스트를 변경할 수도 있다.
- 플로우에서 윗부분에 있는 함수에서만 작동하는 걸 기억해야 한다.
    
![IMG_D4BBAB6B4C09-1](https://github.com/woowacourse-study/2023-BookOverFlow/assets/50761690/0216a6c1-9319-493a-a3d2-2ef38c98f2cf)

    

```kotlin
suspend fun present(place: String, message: String) {
	val ctx = coroutineContext
	val name = ctx[CoroutineName]?.name
	println("[$name] $message on $place")
}

fun messagesFlow(): Flow<String> = flow {
	present("flow builder", "Message")
	emit("Message")
}

suspend fun main() {
	val users = messagesFlow()
	withContext(CoroutineName("Name1")) {
		users
			.flowOn(CoroutineName("Name3"))
			.onEach { present("onEach", it) }
			.flowOn(CoroutineName("Name2"))
			.collect { present("collect", it) }
	}
}
```

- 출력
    
    ```kotlin
    // [Name3] Message on flow builder
    // [Name2] Message on onEach
    // [Name1] Message on collet
    ```
    

## launchIn

collect는 플로우가 완료될 때까지 코루틴을 중단하는 중단 연산

launch 빌더로 collect를 래핑하면 플로우를 다른 코루틴에서 처리할 수 있다.

**launchIn**

- 유일한 인자로 스코프를 받아 collect를 새로운 코루틴에서 시작할 수 있다.
- 별도의 코루틴에서 플로우를 시작하기 위해 주로 사용한다.

```kotlin
fun <T> Flow<T>.launchIn(scope: CoroutineScope): Job = 
	scope.launch { collect() }
```

```kotlin
suspend fun main(): Unit = coroutineScope {
	flowOf("User1", "User2")
		.onStart { println("Users:") }
		.onEach { println(it) }
		.launchInt(this)
}
```

- 출력
    
    ```kotlin
    // Users:
    // User1
    // User2
    ```
    

### 요약

플로우가 시작될 때, 닫힐 때, 또는 각 원소를 탐색할 때 플로우에 작업을 추가할 수 있다.
